### ISSUE TITLE
Do not use math/rand to generate passwords

### ISSUE THREAD

**Issue by dominikschulz** [aviau/gopass#8]
Using math/rand to generate passwords leads to very practical attacks.
Especially when storing generated passwords in git.

Please use crypt/rand instead.

https://github.com/aviau/gopass/blob/master/cmd/gopass/internal/pwgen/pwgen.go#L21

**Comment by aviau** [comment]
c0536fb77037abc4e1b2e50cb085f2b75d1ffb7f
